import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_REVIEWS]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.GET_REVIEW]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_REVIEW]: [USER_ROLES.CLIENT],
  [CONTROLLERS.UPDATE_REVIEW]: [USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_REVIEW]: [USER_ROLES.CLIENT, USER_ROLES.ADMIN],
  [CONTROLLERS.COUNT_REVIEWS]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
};
