import { CONTROLLERS } from './helper/constants.js';
import { USER_ROLES } from '../../common/helpers/constants.js';

export const PERMISSIONS = {
  [CONTROLLERS.LIST_PRODUCTS_TYPES]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.GET_PRODUCT_TYPE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.CREATE_PRODUCT_TYPE]: [USER_ROLES.DEVELOPER, USER_ROLES.ADMIN],
  [CONTROLLERS.UPDATE_PRODUCT_TYPE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.DELETE_PRODUCT_TYPE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.APPROVE_PRODUCT_TYPE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.DECLINE_PRODUCT_TYPE]: [USER_ROLES.ADMIN]
};
