import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helper/constant.js';


export default {
  [CONTROLLERS.GET_COMMENT] : [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.LIST_COMMENTS] : [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.ADD_COMMENT] : [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.UPDATE_COMMENT] : [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_COMMENT] : [USER_ROLES.OWNER, USER_ROLES.CLIENT]
}