import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_VEHICLES]: [USER_ROLES.ADMIN,USER_ROLES.CLIENT],
  [CONTROLLERS.GET_VEHICLE]: [USER_ROLES.ADMIN,USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_VEHICLE]: [USER_ROLES.ADMIN,USER_ROLES.CLIENT],
  [CONTROLLERS.UPDATE_VEHICLE]: [USER_ROLES.ADMIN,USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_VEHICLE]: [USER_ROLES.ADMIN,USER_ROLES.CLIENT],
  [CONTROLLERS.COUNT_VEHICLES]: [USER_ROLES.ADMIN,USER_ROLES.CLIENT],
};
