import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helper/constant.js';

export default {
  [CONTROLLERS.LIST_ROAD_SERVICES]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.GET_ROAD_SERVICE]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.CREATE_ROAD_SERVICE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.UPDATE_ROAD_SERVICE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.DELETE_ROAD_SERVICE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.COUNT_ROAD_SERVICES]: [USER_ROLES.ADMIN]
};
