import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_COUPONS]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.GET_COUPON]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.CREATE_COUPON]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.UPDATE_COUPON]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.DELETE_COUPON]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.COUNT_COUPONS]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.APPLY_COUPON]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER]
};
