import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_MAINTENANCE_CENTERS]: [
    USER_ROLES.ADMIN,
    USER_ROLES.PROVIDER,
    USER_ROLES.CLIENT
  ],
  [CONTROLLERS.GET_MAINTENANCE_CENTER]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_MAINTENANCE_CENTER]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.UPDATE_MAINTENANCE_CENTER]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.COUNT_MAINTENANCE_CENTERS]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.DELETE_MAINTENANCE_CENTERS]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER]
};
