import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_NOTIFICATIONS]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.GET_NOTIFICATION]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.COUNT_NOTIFICATIONS]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_NOTIFICATION]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.CLEAR_NOTIFICATIONS]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_NOTIFICATION]: [USER_ROLES.ADMIN]
};
