import { CONTROLLER } from './helpers/constant.js';
import { USER_ROLES } from '../../common/helpers/constants.js';

export default {
  [CONTROLLER.LIST_CITIES]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLER.GET_CITY]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLER.CREATE_CITY]: [USER_ROLES.DEVELOPER],
  [CONTROLLER.UPDATE_CITY]: [USER_ROLES.DEVELOPER],
  [CONTROLLER.DELETE_CITY]: [USER_ROLES.DEVELOPER],
  [CONTROLLER.COUNT_CITIES]: [USER_ROLES.ADMIN]
};
