import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helper/constant.js';

export default {
  [CONTROLLERS.LIST_ADDRESSES]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.GET_ADDRESS]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_ADDRESS]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.UPDATE_ADDRESS]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_ADDRESS]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.COUNT_ADDRESSES]: [USER_ROLES.OWNER, USER_ROLES.CLIENT]
};