import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helper/constants.js';

export default {
  [CONTROLLERS.LIST_PRODUCTS]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.GET_PRODUCT]: [USER_ROLES.ADMIN, USER_ROLES.CLIENT, USER_ROLES.PROVIDER],
  [CONTROLLERS.CREATE_PRODUCT]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.DELETE_PRODUCT]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.UPDATE_PRODUCT]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.LIST_MAINTENANCE_CENTER_PRODUCTS]: [
    USER_ROLES.ADMIN,
    USER_ROLES.CLIENT,
    USER_ROLES.PROVIDER
  ]
};
