import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_PRODUCTS]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.GET_PRODUCT]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_PRODUCT]: [USER_ROLES.OWNER],
  [CONTROLLERS.DELETE_PRODUCT]: [USER_ROLES.OWNER],
  [CONTROLLERS.UPDATE_PRODUCT]: [USER_ROLES.OWNER],
};