import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_SERVICE_TEMPLATES_BY_ADMIN]: [USER_ROLES.ADMIN],
  [CONTROLLERS.LIST_SERVICE_TEMPLATES_BY_PROVIDER]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.GET_SERVICE_TEMPLATE]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.CREATE_SERVICE_TEMPLATE]: [USER_ROLES.ADMIN],
  [CONTROLLERS.UPDATE_SERVICE_TEMPLATE_ADMIN]: [USER_ROLES.ADMIN],
  [CONTROLLERS.UPDATE_SERVICE_TEMPLATE_PROVIDER]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.REQUEST_SERVICE_TEMPLATE]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.COUNT_SERVICE_TEMPLATES]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.DELETE_SERVICE_TEMPLATES]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.CLONE_SERVICE_TEMPLATE_FOR_PROVIDER]: [USER_ROLES.PROVIDER]
};
