import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_CART]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_CART_PRODUCT]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_CART_PRODUCT]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.CLEAR_CART]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.CHECKOUT]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_CART_PACKAGE]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_CART_PACKAGE]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.UPDATE_CART_PACKAGE]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_CART_PRODUCT]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.UPDATE_CART_PRODUCT]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.INCREASE_PACKAGE_QUANTITY] : [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.DECREASE_PACKAGE_QUANTITY] : [USER_ROLES.OWNER,USER_ROLES.CLIENT],
  [CONTROLLERS.DELETE_CART_PRODUCT]: [USER_ROLES.OWNER, USER_ROLES.CLIENT],
  [CONTROLLERS.APPLY_COUPON] : [USER_ROLES.OWNER, USER_ROLES.CLIENT]
};
