import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.LIST_SERVICES]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.GET_SERVICE]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER, USER_ROLES.CLIENT],
  [CONTROLLERS.CREATE_SERVICE]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.UPDATE_SERVICE]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.COUNT_SERVICES]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER],
  [CONTROLLERS.DELETE_SERVICES]: [USER_ROLES.ADMIN, USER_ROLES.PROVIDER]
};
