import { USER_ROLES } from '../../common/helpers/constants.js';
import { CONTROLLERS } from './helpers/constants.js';

export default {
  [CONTROLLERS.CLIENT_LIST_BOOKINGS]: [USER_ROLES.CLIENT],
  [CONTROLLERS.Provider_LIST_BOOKINGS]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.ADMIN_LIST_BOOKINGS]: [USER_ROLES.ADMIN],
  [CONTROLLERS.GET_BOOKING]: [USER_ROLES.CLIENT,USER_ROLES.PROVIDER,USER_ROLES.ADMIN],
  [CONTROLLERS.CREATE_BOOKING]: [USER_ROLES.CLIENT],
  [CONTROLLERS.UPDATE_BOOKING]: [USER_ROLES.CLIENT,USER_ROLES.PROVIDER],
  [CONTROLLERS.RESCHEDULE_BOOKING]: [USER_ROLES.PROVIDER], 
  [CONTROLLERS.DECLINE_BOOKING]: [USER_ROLES.CLIENT,USER_ROLES.PROVIDER],
  [CONTROLLERS.COMPLETE_BOOKING]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.COUNT_BOOKINGS]: [USER_ROLES.ADMIN,USER_ROLES.CLIENT,USER_ROLES.PROVIDER],
  [CONTROLLERS.APPROVE_CLIENT_BOOKING]: [USER_ROLES.CLIENT],
  [CONTROLLERS.DECLINE_CLIENT_BOOKING]: [USER_ROLES.CLIENT],
  [CONTROLLERS.APPROVE_PROVIDER_BOOKING]: [USER_ROLES.PROVIDER],
  [CONTROLLERS.DECLINE_PROVIDER_BOOKING]: [USER_ROLES.PROVIDER],
};
